version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - webnet
    env_file:
      - backend/.env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3001:80"
    networks:
      - webnet
    env_file:
      - frontend/.env
    depends_on:
      - backend

  postgres:
    image: postgres:14
    container_name: postgres
    networks:
      - webnet
    env_file:
      - postgres/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - pgadmin/.env
    ports:
      - "8080:80"
    networks:
      - webnet
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  pgadmin_data:

networks:
  webnet: